---
version: "2.1"
services:
  frontend:
    build: ./codenames_frontend
    container_name: codenames_frontend
    volumes:
      - www_data:/www
    restart: "no"

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    depends_on:
      - frontend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - URL=codejack.net
      - SUBDOMAINS=www,api
      - VALIDATION=http
      - CERTPROVIDER= zerossl
      - DNSPLUGIN=cloudflare
      - EMAIL=dustinroepsch@gmail.com
      - ONLY_SUBDOMAINS=false
      #- EXTRA_DOMAINS=
      - STAGING=false #optional
    volumes:
      - ./swag/config:/config
      - www_data:/config/www
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

  backend:
    build: ./codenames_backend
    container_name: codenames_backend
    environment:
      - CORS_ORIGIN=https://codejack.net,https://www.codejack.net
    expose:
      - "3001"
    restart: unless-stopped

volumes:
  www_data: